type Book {
  id: ID!
  thumbnail: String!
  writer_id: String!
  is_published: Boolean!
  pages: [Page!]!
}

type Query {
  book(input: BookInput!): Book
}

type Mutation {
  deploy(input: DeployInput!): Void
  build(input: BuildInput!): Void
}

type Subscription {
  bookDeploy(input: DeployInput!): Void
}

input BookInput {
  book_id: ID!
}

input DeployInput {
  book_id: ID!
}

input BuildInput {
  book_id: ID!
}
