type Book {
  id: ID!
  thumbnail: String!
  fk_writer_id: String!
  is_published: Boolean!
  pages: [Page!]!
}

type Query {
  book(input: BookIDInput!): Book
}

type Mutation {
  deploy(input: BookUrlSlugInput!): DeployResult! @auth
  build(input: BookUrlSlugInput!): BuildResult! @auth
}

type Subscription {
  bookBuildInstalled(input: BookUrlSlugInput!): SubScriptionPayload @auth
  bookBuildCompleted(input: BookUrlSlugInput!): SubScriptionPayload @auth
  bookDeployCompleted(input: BookUrlSlugInput!): SubScriptionPayload @auth
}

input BookIDInput {
  book_id: ID!
}

input BookUrlSlugInput {
  url_slug: String!
}

type SubScriptionPayload {
  message: String!
}

type BuildResult {
  result: Boolean!
}

type DeployResult {
  published_url: String
}
