enum PageType {
  page
  separator
}

type Page {
  id: ID!
  writer_id: ID!
  book_id: ID!
  title: String!
  body: String!
  type: PageType!
  parent_id: ID
  index: Int!
  url_slug: String!
  code: String!
  level: Int!
  created_at: Date!
  childrens: [Page!]!
}

type PageMetadata {
  id: ID!
  title: String!
  code: String!
  url_slug: String!
  parent_id: String
  type: String!
  level: Int!
  childrens: [PageMetadata!]!
}

type Query {
  getPageMetadata(input: BookIDInput!): [PageMetadata!]!
}

input BookIDInput {
  book_id: ID!
}
