enum PageType {
  page
  folder
  separator
}

type Page {
  id: ID!
  fk_writer_id: ID!
  book_id: ID!
  title: String!
  body: String!
  type: String!
  parent_id: ID
  index: Int!
  url_slug: String!
  code: String!
  level: Int!
  created_at: Date!
  updated_at: Date!
  childrens: [Page!]!
}

type Query {
  pages(input: GetPagesInput!): [Page!]! @auth
}

type Mutation {
  create(input: CreatePageInput!): Page @auth
  reorder(input: ReorderInput!): Void @auth
}

input GetPagesInput {
  book_url_slug: String!
}

input CreatePageInput {
  title: String!
  index: Int!
  parent_url_slug: String!
  book_url_slug: String!
  type: PageType!
}

input ReorderInput {
  book_url_slug: String!
  target_url_slug: String!
  parent_url_slug: String
  index: Int!
}
