const OK = 'Ok'
const CREATED = 'CREATED'
const BAD_REQUEST = 'BAD_REQUEST'
const UNAUTHORIZED = 'UNAUTHORIZED'
const FORBIDDEN = 'FORBIDDEN'
const NOT_FOUND = 'NOT_FOUND'
const CONFLICT = 'CONFLICT'
const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'

export const HttpStatusMessage = {
  OK,
  CREATED,
  BAD_REQUEST,
  FORBIDDEN,
  UNAUTHORIZED,
  NOT_FOUND,
  CONFLICT,
  INTERNAL_SERVER_ERROR,
}
