const ONE_MINUTE_IN_MS = 1000 * 60
const ONE_HOUR_IN_MS = ONE_MINUTE_IN_MS * 60
const ONE_DAY_IN_MS = ONE_HOUR_IN_MS * 24

const ONE_MINUTE_IN_S = 60
const ONE_HOUR_IN_S = ONE_MINUTE_IN_S * 60
const ONE_DAY_IN_S = ONE_HOUR_IN_S * 24

export const Time = {
  ONE_MINUTE_IN_MS,
  ONE_HOUR_IN_MS,
  ONE_DAY_IN_MS,

  ONE_MINUTE_IN_S,
  ONE_HOUR_IN_S,
  ONE_DAY_IN_S,
}
